### ISSUE TITLE
The "set_AudioLevel -Volume 0" option only reduces the volume to 4

### ISSUE THREAD

**Issue by marceepoonu** [ErikPlachta/PowerShell-Set-AudioLevel#1]
When I run the script in the Windows Powershell ISE, the volume is reduced to 4 instead of zero, and a little window momentarily appears showing the volume level.  I'd be curious to get any hints about what is preventing the level from going to zero, and what triggers the momentary appearance of that window.
<img width="1920" alt="Volume level window" src="https://github.com/ErikPlachta/PowerShell_AudioLevel/assets/529625/bbba0c89-3de4-4bae-884e-382a0f92d958">
[powershell-to-mute-unmute-audio-in-windows_from_Erik-Plachta_aaa.ps1.zip](https://github.com/ErikPlachta/PowerShell_AudioLevel/files/14363317/powershell-to-mute-unmute-audio-in-windows_from_Erik-Plachta_aaa.ps1.zip)

**Comment by ErikPlachta** [comment]
@marceepoonu - Appreciate you pointing out this bug! Hopefully you got a solution, but just in case you didn't I wanted to send this message to let you know I fixed the bug and updated the code.


The For-Each logic `1..$audioLevel | %{...}` was not behaving as I assumed it was.

- Always ran at least once
- Always starting at 1.

Another issue was that the value is increased by 2% each time, causing some weird results.

- Updating the press count value to a double, `/ 2.0`, seems to have resolved the conversion issues.
- That being said, I don't think it's possible to get an odd value.
